M48
; DRILL file KiCad 10.0.5 date 2026-08-13T00:42:15
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-08-13T00:42:15-05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,10.0.5
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.650
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C3.200
%
G90
G05
T1
X147.9Y-109.11
X147.9Y-114.89
T2
X103.5Y-103.5
X103.5Y-136.5
X151.5Y-103.5
X151.5Y-136.5
M30
