M48
; DRILL file KiCad 10.0.5 date 2026-08-13T21:07:56
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-08-13T21:07:56-05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,10.0.5
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.650
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C3.200
%
G90
G05
T1
X138.4Y-114.11
X138.4Y-119.89
T2
X103.5Y-103.5
X103.5Y-130.5
X141.5Y-103.5
X141.5Y-130.5
M30
