[env:lock_c3]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/55.03.39/platform-espressif32.zip
framework = arduino
board = esp32-c3-devkitm-1
monitor_speed = 115200
build_flags =
    -DARDUINO_USB_MODE=1
    -DARDUINO_USB_CDC_ON_BOOT=1
    -DCONFIG_BT_NIMBLE_MAX_CONNECTIONS=1
    -DCORE_DEBUG_LEVEL=1
lib_deps =
    h2zero/NimBLE-Arduino@^2.5.0

[env:lock_c3_debug]
extends = env:lock_c3
build_type = debug
build_flags =
    ${env:lock_c3.build_flags}
    -DCORE_DEBUG_LEVEL=4
